export const drivers = [
  {
    name: "Alex",
    license: "DL-898213",
    category: "LMV",
    expiry: "12/2028",
    contact: "98765xxxxx",
    completion: "96%",
    safety: "Available",
    status: "Available",
  },
  {
    name: "John",
    license: "DL-44120",
    category: "HMV",
    expiry: "03/2025",
    contact: "98320xxxxx",
    completion: "81%",
    safety: "Suspended",
    status: "Suspended",
  },
  {
    name: "Priya",
    license: "DL-77031",
    category: "LMV",
    expiry: "08/2027",
    contact: "99110xxxxx",
    completion: "99%",
    safety: "On Trip",
    status: "On Trip",
  },
  {
    name: "Suresh",
    license: "DL-90045",
    category: "HMV",
    expiry: "01/2037",
    contact: "97440xxxxx",
    completion: "88%",
    safety: "Available",
    status: "Off Duty",
  },
];
